### ISSUE TITLE
Netbox pgsql Issue

### ISSUE THREAD

**Issue by compgeniuses** [geniusdynamics/dev#2]
Traceback (most recent call last):
  File "/home/netbox1/.config/actions/configure-module/10configure_environment_vars", line 36, in <module>
    agent.write_envfile(postgres_config, "postgres.env")
  File "/usr/local/agent/pypkg/agent/__init__.py", line 111, in write_envfile
    entries = [ek + "=" + str(ev) for ek, ev in envmap.items()]
                                                ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'items'

**Comment by kemboi22** [comment]
I think right now its fixed
